apiVersion: v1
kind: ConfigMap
metadata:
  name: access-control-service-config
  namespace: sparc
  labels:
    app: access-control-service
    component: config
data:
  NODE_ENV: "production"
  PORT: "3002"
  LOG_LEVEL: "info"
  METRICS_PORT: "9090"
  HEALTH_CHECK_PORT: "8080"
  REDIS_HOST: "redis-service"
  REDIS_PORT: "6379"
  DATABASE_HOST: "postgres-service"
  DATABASE_PORT: "5432"
  DATABASE_NAME: "sparc"
  JWT_ALGORITHM: "RS256"
  RATE_LIMIT_WINDOW_MS: "900000"
  RATE_LIMIT_MAX_REQUESTS: "100"
  WEBSOCKET_ENABLED: "true"
  WEBSOCKET_PORT: "3003"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: access-control-service
  namespace: sparc
  labels:
    app: access-control-service
    version: v1
    component: microservice
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: access-control-service
  template:
    metadata:
      labels:
        app: access-control-service
        version: v1
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9090"
        prometheus.io/path: "/metrics"
    spec:
      serviceAccountName: sparc-service-account
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      containers:
      - name: access-control-service
        image: sparc/access-control-service:latest
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 3002
          protocol: TCP
        - name: websocket
          containerPort: 3003
          protocol: TCP
        - name: metrics
          containerPort: 9090
          protocol: TCP
        - name: health
          containerPort: 8080
          protocol: TCP
        env:
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: password
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: redis-secret
              key: password
        - name: JWT_PRIVATE_KEY
          valueFrom:
            secretKeyRef:
              name: jwt-secret
              key: private-key
        - name: JWT_PUBLIC_KEY
          valueFrom:
            secretKeyRef:
              name: jwt-secret
              key: public-key
        envFrom:
        - configMapRef:
            name: access-control-service-config
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: health
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /ready
            port: health
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        startupProbe:
          httpGet:
            path: /startup
            port: health
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 30
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
            - ALL
        volumeMounts:
        - name: tmp
          mountPath: /tmp
        - name: logs
          mountPath: /app/logs
      volumes:
      - name: tmp
        emptyDir: {}
      - name: logs
        emptyDir: {}
      terminationGracePeriodSeconds: 30

---
apiVersion: v1
kind: Service
metadata:
  name: access-control-service
  namespace: sparc
  labels:
    app: access-control-service
    component: service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 3002
    targetPort: http
    protocol: TCP
  - name: websocket
    port: 3003
    targetPort: websocket
    protocol: TCP
  - name: metrics
    port: 9090
    targetPort: metrics
    protocol: TCP
  selector:
    app: access-control-service

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: access-control-service-hpa
  namespace: sparc
  labels:
    app: access-control-service
    component: autoscaler
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: access-control-service
  minReplicas: 3
  maxReplicas: 15
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 10
        periodSeconds: 60
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
      - type: Percent
        value: 50
        periodSeconds: 60

---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: access-control-service-pdb
  namespace: sparc
  labels:
    app: access-control-service
    component: disruption-budget
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app: access-control-service

---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: access-control-service-netpol
  namespace: sparc
  labels:
    app: access-control-service
    component: network-policy
spec:
  podSelector:
    matchLabels:
      app: access-control-service
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: api-gateway
    - podSelector:
        matchLabels:
          app: web-frontend
    - namespaceSelector:
        matchLabels:
          name: monitoring
      podSelector:
        matchLabels:
          app: prometheus
    ports:
    - protocol: TCP
      port: 3002
    - protocol: TCP
      port: 3003
    - protocol: TCP
      port: 9090
  egress:
  - to:
    - podSelector:
        matchLabels:
          app: postgres
    ports:
    - protocol: TCP
      port: 5432
  - to:
    - podSelector:
        matchLabels:
          app: redis
    ports:
    - protocol: TCP
      port: 6379
  - to:
    - podSelector:
        matchLabels:
          app: auth-service
    ports:
    - protocol: TCP
      port: 3001
  - to:
    - podSelector:
        matchLabels:
          app: event-processing-service
    ports:
    - protocol: TCP
      port: 3007
  - to: []
    ports:
    - protocol: TCP
      port: 53
    - protocol: UDP
      port: 53

---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: access-control-service-monitor
  namespace: sparc
  labels:
    app: access-control-service
    component: monitoring
spec:
  selector:
    matchLabels:
      app: access-control-service
  endpoints:
  - port: metrics
    path: /metrics
    interval: 30s
    scrapeTimeout: 10s
    honorLabels: true
  namespaceSelector:
    matchNames:
    - sparc

---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: access-control-service-alerts
  namespace: sparc
  labels:
    app: access-control-service
    component: alerting
spec:
  groups:
  - name: access-control-service.rules
    rules:
    - alert: AccessControlServiceDown
      expr: up{job="access-control-service"} == 0
      for: 1m
      labels:
        severity: critical
        service: access-control-service
      annotations:
        summary: "Access Control Service is down"
        description: "Access Control Service has been down for more than 1 minute"
    
    - alert: AccessControlServiceHighErrorRate
      expr: rate(http_requests_total{job="access-control-service",status=~"5.."}[5m]) > 0.1
      for: 5m
      labels:
        severity: warning
        service: access-control-service
      annotations:
        summary: "High error rate in Access Control Service"
        description: "Access Control Service error rate is {{ $value }} errors per second"
    
    - alert: AccessControlServiceHighLatency
      expr: histogram_quantile(0.95, rate(http_request_duration_seconds_bucket{job="access-control-service"}[5m])) > 1
      for: 5m
      labels:
        severity: warning
        service: access-control-service
      annotations:
        summary: "High latency in Access Control Service"
        description: "Access Control Service 95th percentile latency is {{ $value }}s"
    
    - alert: AccessControlServiceHighMemoryUsage
      expr: container_memory_usage_bytes{pod=~"access-control-service-.*"} / container_spec_memory_limit_bytes > 0.9
      for: 5m
      labels:
        severity: warning
        service: access-control-service
      annotations:
        summary: "High memory usage in Access Control Service"
        description: "Access Control Service memory usage is above 90%"
    
    - alert: AccessControlServiceHighCPUUsage
      expr: rate(container_cpu_usage_seconds_total{pod=~"access-control-service-.*"}[5m]) / container_spec_cpu_quota * 100 > 80
      for: 5m
      labels:
        severity: warning
        service: access-control-service
      annotations:
        summary: "High CPU usage in Access Control Service"
        description: "Access Control Service CPU usage is above 80%"
    
    - alert: AccessControlServiceReplicasNotReady
      expr: kube_deployment_status_replicas_ready{deployment="access-control-service"} < 2
      for: 2m
      labels:
        severity: critical
        service: access-control-service
      annotations:
        summary: "Access Control Service has insufficient ready replicas"
        description: "Access Control Service has {{ $value }} ready replicas, minimum required is 2"
    
    - alert: AccessControlServiceWebSocketConnectionsHigh
      expr: websocket_connections_total{job="access-control-service"} > 1000
      for: 5m
      labels:
        severity: warning
        service: access-control-service
      annotations:
        summary: "High WebSocket connections in Access Control Service"
        description: "Access Control Service has {{ $value }} active WebSocket connections"
    
    - alert: AccessControlServiceDatabaseConnectionsHigh
      expr: database_connections_active{job="access-control-service"} > 50
      for: 5m
      labels:
        severity: warning
        service: access-control-service
      annotations:
        summary: "High database connections in Access Control Service"
        description: "Access Control Service has {{ $value }} active database connections"