apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-documentation-service
  namespace: sparc
  labels:
    app: api-documentation-service
    component: backend
    tier: service
    version: v1
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: api-documentation-service
  template:
    metadata:
      labels:
        app: api-documentation-service
        component: backend
        tier: service
        version: v1
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "3001"
        prometheus.io/path: "/metrics"
    spec:
      serviceAccountName: api-documentation-service
      securityContext:
        runAsNonRoot: true
        runAsUser: 1001
        runAsGroup: 1001
        fsGroup: 1001
      containers:
      - name: api-documentation-service
        image: sparc/api-documentation-service:latest
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 3001
          protocol: TCP
        env:
        - name: NODE_ENV
          value: "production"
        - name: PORT
          value: "3001"
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: sparc-secrets
              key: database-url
        - name: REDIS_URL
          valueFrom:
            secretKeyRef:
              name: sparc-secrets
              key: redis-url
        - name: SERVICE_DISCOVERY_ENABLED
          valueFrom:
            configMapKeyRef:
              name: api-documentation-config
              key: service-discovery-enabled
        - name: OPENAPI_GENERATION_INTERVAL
          valueFrom:
            configMapKeyRef:
              name: api-documentation-config
              key: openapi-generation-interval
        - name: SDK_GENERATION_ENABLED
          valueFrom:
            configMapKeyRef:
              name: api-documentation-config
              key: sdk-generation-enabled
        - name: DEVELOPER_PORTAL_ENABLED
          valueFrom:
            configMapKeyRef:
              name: api-documentation-config
              key: developer-portal-enabled
        - name: API_GATEWAY_URL
          valueFrom:
            configMapKeyRef:
              name: api-documentation-config
              key: api-gateway-url
        - name: SWAGGER_UI_THEME
          valueFrom:
            configMapKeyRef:
              name: api-documentation-config
              key: swagger-ui-theme
        - name: CORS_ORIGIN
          valueFrom:
            configMapKeyRef:
              name: sparc-config
              key: cors-origin
        - name: LOG_LEVEL
          valueFrom:
            configMapKeyRef:
              name: sparc-config
              key: log-level
        - name: RATE_LIMIT_WINDOW_MS
          valueFrom:
            configMapKeyRef:
              name: sparc-config
              key: rate-limit-window-ms
        - name: RATE_LIMIT_MAX_REQUESTS
          valueFrom:
            configMapKeyRef:
              name: sparc-config
              key: rate-limit-max-requests
        - name: GITHUB_TOKEN
          valueFrom:
            secretKeyRef:
              name: sparc-secrets
              key: github-token
              optional: true
        - name: NPM_TOKEN
          valueFrom:
            secretKeyRef:
              name: sparc-secrets
              key: npm-token
              optional: true
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: http
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /ready
            port: http
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          successThreshold: 1
          failureThreshold: 3
        startupProbe:
          httpGet:
            path: /health
            port: http
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          successThreshold: 1
          failureThreshold: 30
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 1001
          runAsGroup: 1001
          capabilities:
            drop:
            - ALL
        volumeMounts:
        - name: tmp
          mountPath: /tmp
        - name: logs
          mountPath: /app/logs
        - name: generated-docs
          mountPath: /app/generated
        - name: sdk-cache
          mountPath: /app/sdk-cache
      volumes:
      - name: tmp
        emptyDir: {}
      - name: logs
        emptyDir: {}
      - name: generated-docs
        emptyDir:
          sizeLimit: 1Gi
      - name: sdk-cache
        emptyDir:
          sizeLimit: 2Gi
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - api-documentation-service
              topologyKey: kubernetes.io/hostname
      tolerations:
      - key: "sparc.io/api-documentation-service"
        operator: "Equal"
        value: "true"
        effect: "NoSchedule"

---
apiVersion: v1
kind: Service
metadata:
  name: api-documentation-service
  namespace: sparc
  labels:
    app: api-documentation-service
    component: backend
    tier: service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "http"
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 80
    targetPort: http
    protocol: TCP
  selector:
    app: api-documentation-service

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: api-documentation-service
  namespace: sparc
  labels:
    app: api-documentation-service
    component: backend
    tier: service
automountServiceAccountToken: true

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: api-documentation-service
  labels:
    app: api-documentation-service
    component: backend
    tier: service
rules:
- apiGroups: [""]
  resources: ["services", "endpoints"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["networking.k8s.io"]
  resources: ["ingresses"]
  verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: api-documentation-service
  labels:
    app: api-documentation-service
    component: backend
    tier: service
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: api-documentation-service
subjects:
- kind: ServiceAccount
  name: api-documentation-service
  namespace: sparc

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: api-documentation-service-hpa
  namespace: sparc
  labels:
    app: api-documentation-service
    component: backend
    tier: service
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: api-documentation-service
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 10
        periodSeconds: 60
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
      - type: Percent
        value: 50
        periodSeconds: 60
      - type: Pods
        value: 2
        periodSeconds: 60
      selectPolicy: Max

---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: api-documentation-service-pdb
  namespace: sparc
  labels:
    app: api-documentation-service
    component: backend
    tier: service
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: api-documentation-service

---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: api-documentation-service-netpol
  namespace: sparc
  labels:
    app: api-documentation-service
    component: backend
    tier: service
spec:
  podSelector:
    matchLabels:
      app: api-documentation-service
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          name: sparc
    - podSelector:
        matchLabels:
          app: api-gateway
    - podSelector:
        matchLabels:
          app: nginx-ingress
    - podSelector: {}
    ports:
    - protocol: TCP
      port: 3012
  egress:
  - to:
    - namespaceSelector:
        matchLabels:
          name: sparc
    - podSelector:
        matchLabels:
          app: postgresql
    ports:
    - protocol: TCP
      port: 5432
  - to:
    - namespaceSelector:
        matchLabels:
          name: sparc
    - podSelector:
        matchLabels:
          app: redis
    ports:
    - protocol: TCP
      port: 6379
  - to:
    - namespaceSelector:
        matchLabels:
          name: sparc
    - podSelector: {}
    ports:
    - protocol: TCP
      port: 80
    - protocol: TCP
      port: 3012
  - to: []
    ports:
    - protocol: TCP
      port: 53
    - protocol: UDP
      port: 53
  - to: []
    ports:
    - protocol: TCP
      port: 443
    - protocol: TCP
      port: 80

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: api-documentation-config
  namespace: sparc
  labels:
    app: api-documentation-service
    component: config
data:
  service-discovery-enabled: "true"
  openapi-generation-interval: "300"
  sdk-generation-enabled: "true"
  developer-portal-enabled: "true"
  api-gateway-url: "http://api-gateway.sparc.svc.cluster.local"
  swagger-ui-theme: "sparc"
  api-version-retention: "12"
  sdk-languages: "javascript,python,csharp,java,go,php"
  documentation-cache-ttl: "3600"
  webhook-documentation-enabled: "true"
  error-code-documentation-enabled: "true"
  api-usage-analytics-enabled: "true"
  developer-sandbox-enabled: "true"
  rate-limit-documentation: "true"
  authentication-examples-enabled: "true"

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api-documentation-service-ingress
  namespace: sparc
  labels:
    app: api-documentation-service
    component: backend
    tier: service
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "300"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "300"
    nginx.ingress.kubernetes.io/rate-limit: "100"
    nginx.ingress.kubernetes.io/rate-limit-window: "1m"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/cors-allow-origin: "*"
    nginx.ingress.kubernetes.io/cors-allow-methods: "GET, POST, OPTIONS"
    nginx.ingress.kubernetes.io/cors-allow-headers: "DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range,Authorization"
    nginx.ingress.kubernetes.io/enable-cors: "true"
spec:
  tls:
  - hosts:
    - docs.sparc.example.com
    - api-docs.sparc.example.com
    secretName: api-documentation-tls
  rules:
  - host: docs.sparc.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: api-documentation-service
            port:
              number: 80
  - host: api-docs.sparc.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: api-documentation-service
            port:
              number: 80

---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: api-documentation-service
  namespace: sparc
  labels:
    app: api-documentation-service
    component: backend
    tier: service
spec:
  selector:
    matchLabels:
      app: api-documentation-service
  endpoints:
  - port: http
    path: /metrics
    interval: 30s
    scrapeTimeout: 10s

---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: api-documentation-service-alerts
  namespace: sparc
  labels:
    app: api-documentation-service
    component: backend
    tier: service
    prometheus: sparc
    role: alert-rules
spec:
  groups:
  - name: api-documentation-service.rules
    rules:
    - alert: APIDocumentationServiceDown
      expr: up{job="api-documentation-service"} == 0
      for: 1m
      labels:
        severity: critical
        service: api-documentation-service
      annotations:
        summary: "API Documentation Service is down"
        description: "API Documentation Service has been down for more than 1 minute"
    
    - alert: APIDocumentationServiceHighMemoryUsage
      expr: (container_memory_working_set_bytes{pod=~"api-documentation-service-.*"} / container_spec_memory_limit_bytes{pod=~"api-documentation-service-.*"}) * 100 > 85
      for: 5m
      labels:
        severity: warning
        service: api-documentation-service
      annotations:
        summary: "API Documentation Service high memory usage"
        description: "API Documentation Service memory usage is above 85% for more than 5 minutes"
    
    - alert: APIDocumentationServiceHighCPUUsage
      expr: (rate(container_cpu_usage_seconds_total{pod=~"api-documentation-service-.*"}[5m]) * 100) > 80
      for: 5m
      labels:
        severity: warning
        service: api-documentation-service
      annotations:
        summary: "API Documentation Service high CPU usage"
        description: "API Documentation Service CPU usage is above 80% for more than 5 minutes"
    
    - alert: APIDocumentationServiceHighErrorRate
      expr: (rate(http_requests_total{job="api-documentation-service",status=~"5.."}[5m]) / rate(http_requests_total{job="api-documentation-service"}[5m])) * 100 > 5
      for: 2m
      labels:
        severity: warning
        service: api-documentation-service
      annotations:
        summary: "API Documentation Service high error rate"
        description: "API Documentation Service error rate is above 5% for more than 2 minutes"
    
    - alert: APIDocumentationServiceSlowResponse
      expr: histogram_quantile(0.95, rate(http_request_duration_seconds_bucket{job="api-documentation-service"}[5m])) > 2
      for: 5m
      labels:
        severity: warning
        service: api-documentation-service
      annotations:
        summary: "API Documentation Service slow response time"
        description: "API Documentation Service 95th percentile response time is above 2 seconds for more than 5 minutes"
    
    - alert: APIDocumentationServiceDocumentationGenerationFailed
      expr: increase(api_documentation_generation_failures_total[5m]) > 3
      for: 1m
      labels:
        severity: warning
        service: api-documentation-service
      annotations:
        summary: "API Documentation generation failures"
        description: "API Documentation Service has failed to generate documentation more than 3 times in the last 5 minutes"
    
    - alert: APIDocumentationServiceSDKGenerationFailed
      expr: increase(api_documentation_sdk_generation_failures_total[10m]) > 2
      for: 1m
      labels:
        severity: warning
        service: api-documentation-service
      annotations:
        summary: "SDK generation failures"
        description: "API Documentation Service has failed to generate SDKs more than 2 times in the last 10 minutes"
    
    - alert: APIDocumentationServiceServiceDiscoveryFailed
      expr: increase(api_documentation_service_discovery_failures_total[5m]) > 5
      for: 2m
      labels:
        severity: critical
        service: api-documentation-service
      annotations:
        summary: "Service discovery failures"
        description: "API Documentation Service has failed service discovery more than 5 times in the last 5 minutes"