export enum ComplianceFramework {
  SOC2 = 'SOC2',
  HIPAA = 'HIPAA',
  PCI_DSS = 'PCI_DSS',
  GDPR = 'GDPR',
  ISO27001 = 'ISO27001',
  NIST = 'NIST',
  CCPA = 'CCPA',
  FISMA = 'FISMA'
}

export enum AuditAction {
  CREATE = 'CREATE',
  READ = 'READ',
  UPDATE = 'UPDATE',
  DELETE = 'DELETE',
  LOGIN = 'LOGIN',
  LOGOUT = 'LOGOUT',
  LOGIN_FAILED = 'LOGIN_FAILED',
  ACCESS_GRANTED = 'ACCESS_GRANTED',
  ACCESS_DENIED = 'ACCESS_DENIED',
  EXPORT = 'EXPORT',
  IMPORT = 'IMPORT',
  APPROVE = 'APPROVE',
  REJECT = 'REJECT',
  ESCALATE = 'ESCALATE',
  ARCHIVE = 'ARCHIVE',
  RESTORE = 'RESTORE',
  CONFIGURATION_CHANGE = 'CONFIGURATION_CHANGE',
  PERMISSION_CHANGE = 'PERMISSION_CHANGE',
  SECURITY_INCIDENT = 'SECURITY_INCIDENT',
  COMPLIANCE_CHECK = 'COMPLIANCE_CHECK',
  POLICY_VIOLATION = 'POLICY_VIOLATION',
  DATA_BREACH = 'DATA_BREACH'
}

export enum ResourceType {
  USER = 'USER',
  ROLE = 'ROLE',
  PERMISSION = 'PERMISSION',
  CAMERA = 'CAMERA',
  DOOR = 'DOOR',
  SENSOR = 'SENSOR',
  ALERT = 'ALERT',
  INCIDENT = 'INCIDENT',
  REPORT = 'REPORT',
  CONFIGURATION = 'CONFIGURATION',
  AUDIT_LOG = 'AUDIT_LOG',
  COMPLIANCE_REPORT = 'COMPLIANCE_REPORT',
  SECURITY_POLICY = 'SECURITY_POLICY',
  DATA_EXPORT = 'DATA_EXPORT',
  ENCRYPTION_KEY = 'ENCRYPTION_KEY',
  CERTIFICATE = 'CERTIFICATE',
  SYSTEM = 'SYSTEM'
}

export enum Severity {
  CRITICAL = 'CRITICAL',
  HIGH = 'HIGH',
  MEDIUM = 'MEDIUM',
  LOW = 'LOW',
  INFO = 'INFO'
}

export enum ComplianceStatus {
  COMPLIANT = 'COMPLIANT',
  NON_COMPLIANT = 'NON_COMPLIANT',
  PARTIAL = 'PARTIAL',
  PENDING = 'PENDING',
  NOT_APPLICABLE = 'NOT_APPLICABLE'
}

export enum DataClassification {
  PUBLIC = 'PUBLIC',
  INTERNAL = 'INTERNAL',
  CONFIDENTIAL = 'CONFIDENTIAL',
  RESTRICTED = 'RESTRICTED',
  TOP_SECRET = 'TOP_SECRET'
}

export enum RetentionStatus {
  ACTIVE = 'ACTIVE',
  ARCHIVED = 'ARCHIVED',
  PENDING_DELETION = 'PENDING_DELETION',
  DELETED = 'DELETED',
  HOLD = 'HOLD'
}

export enum PolicyType {
  ACCESS_CONTROL = 'ACCESS_CONTROL',
  DATA_RETENTION = 'DATA_RETENTION',
  ENCRYPTION = 'ENCRYPTION',
  PASSWORD = 'PASSWORD',
  SESSION = 'SESSION',
  AUDIT = 'AUDIT',
  EXPORT = 'EXPORT',
  NOTIFICATION = 'NOTIFICATION',
  INCIDENT_RESPONSE = 'INCIDENT_RESPONSE',
  BACKUP = 'BACKUP'
}

export enum PolicyAction {
  ALLOW = 'ALLOW',
  DENY = 'DENY',
  REQUIRE_MFA = 'REQUIRE_MFA',
  REQUIRE_APPROVAL = 'REQUIRE_APPROVAL',
  LOG = 'LOG',
  ALERT = 'ALERT',
  BLOCK = 'BLOCK',
  QUARANTINE = 'QUARANTINE'
}

export enum GDPRRequestType {
  ACCESS = 'ACCESS',
  RECTIFICATION = 'RECTIFICATION',
  ERASURE = 'ERASURE',
  PORTABILITY = 'PORTABILITY',
  RESTRICTION = 'RESTRICTION',
  OBJECTION = 'OBJECTION'
}

export enum GDPRRequestStatus {
  PENDING = 'PENDING',
  IN_PROGRESS = 'IN_PROGRESS',
  COMPLETED = 'COMPLETED',
  REJECTED = 'REJECTED',
  PARTIALLY_COMPLETED = 'PARTIALLY_COMPLETED'
}

export enum ScanType {
  VULNERABILITY = 'VULNERABILITY',
  DEPENDENCY = 'DEPENDENCY',
  CODE_QUALITY = 'CODE_QUALITY',
  CONFIGURATION = 'CONFIGURATION',
  COMPLIANCE = 'COMPLIANCE',
  PENETRATION = 'PENETRATION'
}

export enum ScanStatus {
  QUEUED = 'QUEUED',
  IN_PROGRESS = 'IN_PROGRESS',
  COMPLETED = 'COMPLETED',
  FAILED = 'FAILED',
  CANCELLED = 'CANCELLED'
}